export const singlePostPath = `http://${process.env.REACT_APP_BASE_URL}:${process.env.REACT_APP_BASE_PORT}/feed/post/`;
export const statusPath = `http://${process.env.REACT_APP_BASE_URL}:${process.env.REACT_APP_BASE_PORT}/auth/status`;
export const imagePath = `http://${process.env.REACT_APP_BASE_URL}:${process.env.REACT_APP_BASE_PORT}/`;
export const postPath = `http://${process.env.REACT_APP_BASE_URL}:${process.env.REACT_APP_BASE_PORT}/feed/posts?page=`;
export const createPostPath = `http://${process.env.REACT_APP_BASE_URL}:${process.env.REACT_APP_BASE_PORT}/feed/post`;
export const updatePostPath = `http://${process.env.REACT_APP_BASE_URL}:${process.env.REACT_APP_BASE_PORT}/feed/post/`;
export const socketIOPath = `http://${process.env.REACT_APP_BASE_URL}:${process.env.REACT_APP_BASE_PORT}`;
export const loginPath = `http://${process.env.REACT_APP_BASE_URL}:${process.env.REACT_APP_BASE_PORT}/auth/login`;
export const signupPath = `http://${process.env.REACT_APP_BASE_URL}:${process.env.REACT_APP_BASE_PORT}/auth/signup`;
